### ISSUE TITLE
Could not find remote branch 5.3.0 to clone.

### ISSUE THREAD

**Issue by Natelegreat1** [startupthekid/feathers-swift-socketio#15]
I have been trying to install FeathersSwiftSocketIO via Cocoapods.
Something seems to have broken... but I am not sure when it happened.
All my previously-functional branches are now blocked.

I have tried re-starting Mac OS, clearing DerivedData, etc... Suggestions?
 
`Could not find remote branch 5.3.0 to clone.`

<img width="571" alt="Screen Shot 2019-06-26 at 9 23 29 PM" src="https://user-images.githubusercontent.com/2666640/60226847-fa941c80-985a-11e9-9365-d378d3576e5f.png">

**Comment by OstapHolub** [comment]
@Natelegreat1 thank you for reaching out. We updated this repo to support Swift 5 recently and everything looks good. We will definitely check this issue and we will get back to you as soon as we have some results.

**Comment by Natelegreat1** [comment]
@OstapHolub My product is compiled in Swift 5 (Xcode Version 10.2.1 (10E1001)). Thanks! :)
