### ISSUE TITLE
SocketIO updates

### ISSUE THREAD

**Issue by aabanaag** [startupthekid/feathers-swift-socketio#4]
Just recently socketIO updated to v13 and there are breaking changes.

Also ReactiveSwift just dropped a new version and it causes the build failed.

![image](https://user-images.githubusercontent.com/2245822/32991661-7b32918a-cd7a-11e7-9e68-5a486e613733.png)

https://nuclearace.github.io/Socket.IO-Client-Swift/12to13.html

**Comment by thebarndog** [comment]
Ok thanks for the heads up
