### ISSUE TITLE
Some more Syntax Issues w/ SocketIO and Reactive Swift

### ISSUE THREAD

**Issue by raymundcat** [startupthekid/feathers-swift-socketio#6]
Hello, I seem to have found some more issues/syntax conflicts with the dependencies:
![screen shot 2017-11-28 at 6 38 37 pm](https://user-images.githubusercontent.com/4937515/33315401-96edf0ac-d46b-11e7-95dd-3d36c2bc5786.png)
![screen shot 2017-11-28 at 6 38 17 pm](https://user-images.githubusercontent.com/4937515/33315404-97155c32-d46b-11e7-8fa3-b352eaec2e2a.png)
![screen shot 2017-11-28 at 6 38 04 pm](https://user-images.githubusercontent.com/4937515/33315406-973b9c3a-d46b-11e7-88f8-12d570569021.png)

**Comment by aabanaag** [comment]
This is due to the recent updates of ReactiveSwift and SocketIO Client.

**Comment by raymundcat** [comment]
oks thanks for the info. wondering is someone's already working on this..

**Comment by aabanaag** [comment]
I'm also waiting for the updates. I forked this repo and applied the fixes my self but couldn't make my PR pass so I rejected it. hehe

**Comment by raymundcat** [comment]
i saw your fork, and funny enough we ended up applying the almost the same fixes. i think you should PR anyways.

**Comment by thebarndog** [comment]
I'm working on updating now @aabanaag @raymundcat

**Comment by thebarndog** [comment]
Should be resolved by #7 and #8
